### ISSUE TITLE
STU3 Json schema for Allergy intolerance and transactions results in Bad request error even with correct payload

### ISSUE THREAD

**Issue by shrutivardhan1411** [awslabs/fhir-works-on-aws-deployment#261]
1.	**Allergy Intolerance**: The Category attribute is an array of enum values. The Json structure as described, does not allow to include {“category”: [“food”]} in payload. Since enum is a property of items, it should be included in items filed.
{
  "description": "Category of the identified substance.",
`{ "type": "array",
  "enum": [
    "food",
    "medication",
    "environment",
    "biologic"
  ],
  "items": {
    "type": "string"
  }
}`
2.	**Bundle**:  Transaction requests  for create and update interaction (POST and PUT methods: [Input])(http://hl7.org/fhir/stu3/bundle-transaction.json.html) fail with Bad request error for all resources due to a oneOf JSON property in the ResourceList.  _**For Ex: While Posting a Patient resource using transactions, Error occurred due to a failed validation where the patient Resource in the bundle entry matches with Patient, DomainResource, Parameters<Listed twice in the ResourceList> and Resource schemas.**_

**Comment by carvantes** [comment]
Hi, 
Thanks for the very detailed report. I've submitted a PR to fix both issues. We'll be releasing the fix in the next few days.

**Comment by carvantes** [comment]
Hi, the fix has been released. 

The fix is part of [fhir-works-on-aws-routing@5.1.0](https://github.com/awslabs/fhir-works-on-aws-routing/releases/tag/v5.1.0) and the deployment package has been updated to use [the latest version of fhir-works-on-aws-routing](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/9daa3d88ae8a6e33064fdcea77843b53b7d4d3c0/package.json#L44)
