### ISSUE TITLE
Archiving Support

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#290]
I have privacy requirements that some of a patient's online data is archived offline after 6 months for a period of 10 years. Specifically, the AuditEvent resource where the entity is a patient. Looking through the code, I think there's 2 paths that make sense but want to double check that I'm not missing a better way to implement archiving. Ideally, I'll be doing a PR from my fork here as well.

1. Create an AWS Glue job similar to the bulk export job where the input is the `resource-db-$stage` dynamoDB table and it filters the dataframe based on some configurable archiving rules. From there, the job would write the results to an s3 bucket that could have configurable lifecycle rules for cost optimization. There would also need to be logic here somehow to delete data from the Elastic Search indexes as well. Not sure if we could refactor the current dynamoDB change data capture logic for ES to be pubsub so we can have multiple producers.
2. Add a dynamoDB TTL field to the `resource-db-$stage` table and logic in the persistence-ddb to set the TTL field for configurable resourceTypes and periods. Then use kinesis firehose to listen for system deletes on the dynamodb change data capture stream. This feels cleaner and would have better code reuse but makes the storage abstraction requirements higher and a bit more coupled to DynamoDb.

Another wrinkle is that I will need to implement GDPR/CCPA delete and export in the archives themselves later. It feels like another db table here that maps patient uuid to a set of archive files makes sense. Otherwise, using Glue/Athena's ability to select $path from archives where uuid=patientId would work at smaller scales. 

Am I missing another option here that makes sense and would be a bit easier to implement?

**Comment by nguyen102** [comment]
Option 2 looks like a good choice. As you mentioned, you can set the TTL field to have the AuditEvent expire after 6 months. When it expire, this will kick off a DDB Stream event. We currently have a lambda function called ddbToEs. This lambda functions propogate changes from DDB to ES. In conjunction to that responsibility you can edit the lambda function to send batches of DELETES to Firehose. Firehose will then write that data to S3 as you mentioned. Another note: remember to ensure that the ddbToES lambda can read DELETES triggered by the TTL event and write that change to ES. 

In terms of being able to delete the archived files later on, a mapping of Patient UUID to archived file makes sense. To my knowledge, Glue/Athena requires the data to be hosted on AWS, for example S3. However, if you're storing the data offline and on premise, Glue/Athena won't have access to that data. Using DDB to store that mapping would work. Depending on the number of records you're archiving, you could store that mapping locally instead of on DDB.

**Comment by Zambonilli** [comment]
Thanks for the feedback @nguyen102! I'll start down the path of DDB TTLs with firehose and store a uid -> archive files[] and let you know if I hit any troubles.

**Comment by nguyen102** [comment]
Sounds good @Zambonilli. In that case, I'll close this issue for now. Feel free to open another issue if you have any more questions.

**Comment by Zambonilli** [comment]
@nguyen102 I have the code and infrastructure changes required for archiving completed in my personal forks of interface, routing, persistence-ddb and deployment. I'm not sure how you normally merge PRs going across repos since there are module dependencies here. So, I started by opening a PR for the interface and updated all dependencies to use git URLs to my fork. We can cascade downwards here and publish each individually/update dependency or if it's easier we can merge all then update to published versions. Just let me know.

Also, do you want this ticket opened again?

interface PR
https://github.com/awslabs/fhir-works-on-aws-interface/pull/64

Forks
https://github.com/Zambonilli/fhir-works-on-aws-interface
https://github.com/Zambonilli/fhir-works-on-aws-persistence-ddb
https://github.com/Zambonilli/fhir-works-on-aws-routing
https://github.com/Zambonilli/fhir-works-on-aws-deployment
