### ISSUE TITLE
Not able to search resource identifier exactly.

### ISSUE THREAD

**Issue by rhinozD** [awslabs/fhir-works-on-aws-deployment#301]
Hi FHIR Works Team,
I tried to:
`GET /Patient?identifier=testuser01@gmail.com`
and there is only one patient with `identifier = testuser01@gmail.com`.
I expect it to return one result, but it returns many more.

Is this a bug?
Deployed fhir-works-on-aws-deployment version: v2.6.0

**Comment by carvantes** [comment]
Hi,

Thanks for the detailed report. We have identified the issue and are working on fixing it.

Turns out that the `identifier` param was resulting in text search queries instead of exact text matching. 
e.g. `testuser01@gmail.com` was analyzed into words before searching: `testuser0`,`gmail.com`. This ended up matching unwanted records with a `gmail.com` address

**Comment by carvantes** [comment]
We just released fhir-works-on-aws-search-es@2.5.1 that includes the above fix.

We'll be updating the deployment package later this week as well, but you can upgrade to the latest fhir-works-on-aws-search-es if you need the fix asap.
