### ISSUE TITLE
Search for multiple identifiers

### ISSUE THREAD

**Issue by phackwer** [awslabs/fhir-works-on-aws-deployment#304]
Hi,

In our system we will have patient data coming from multiple different systems. We can try to manage this through the managingOrganization attribute, but we also would like to be able to search for multiple identifiers. I've tried sending a comma separated list and it didn't work. Also tried "php style" array (?identifier[]=...&identififier[]=...) which ended up causing a 500 error.

Since in our case patients get multiple identifiers as the source of the data may be different EPR systems, we want the patient to be able to see his data only refering that EPR system instance, so, we would save 3 identifiers: NHS number, our internal Patient UUID and the remote system UUID. We need this multiple search as we need to make all different combinations for searching patients data and prevent crossing between different systems.

How is the search for multiple identifiers supposed to be done?

**Comment by phackwer** [comment]
Oh, found a way...

The multiple identifiers must be separated by comma and space.

Like https://......execute-api.eu-west-1.amazonaws.com/dev/Patient/?identifier=9........5, 9........3

They also can be placed inside brackets, no problem there, but if you don't put the space, it won't work. My problem was I've missed the space. 

Now my problem is different: how can I get the result as an AND and not an OR.

**Comment by phackwer** [comment]
I'm trying the search as defined in the FHIR 4 spec and it doesn't work.

https://www.hl7.org/fhir/search.html

![image](https://user-images.githubusercontent.com/4871786/116530253-bc903580-a8d5-11eb-8291-8d7f1497be21.png)

![image](https://user-images.githubusercontent.com/4871786/116529109-7ab2bf80-a8d4-11eb-9692-63ca720f4e8e.png)

**Comment by phackwer** [comment]
Ok, now I've got confused, hahaha. I've tried to use the | between the identifiers and all I've got as answer was...

1

:-) 

![image](https://user-images.githubusercontent.com/4871786/116529865-4b508280-a8d5-11eb-8667-e56b2419c031.png)

**Comment by phackwer** [comment]
Is there any documentation on AWS FHIR Works search available? The Postman Collection seems not to cover the options and not all the FHIR specification is implemented yet. If we could know how far the search implementation has gone it would help us a lot to avoid errors using it. 

Thank you

**Comment by carvantes** [comment]
Hi, 

you are right in that searching by multiple identifiers should be done by using commas:

e.g. `GET [base]/Patient?identifier=id1,id2,http://acme.org/patient|2345`

However, we currently do not support the OR operator(`,`) so the queries will take the comma literally as part of the identifier and lead to unexpected results.

https://www.hl7.org/fhir/search.html#composite

---

> Now my problem is different: how can I get the result as an AND and not an OR.

Searching for patients that match several identifiers can be achieved using repeated query parameters.

e.g. `GET [base]/Patient?identifier=id1&identifier=id2` 

This is supported.

---

> Ok, now I've got confused, hahaha. I've tried to use the | between the identifiers and all I've got as answer was...
> 1

It is actually an empty 400 response. The "1" is the line number in the postman UI. This occurs since the vertical bar (`|`) must be URL-encoded.

`GET [base]/Patient?identifier=8|8` must be encoded to  `GET [base]/Patient?identifier=8%7C8`

This is rarely an issue when calling our FHIR server programmatically since most http client libraries do URL encoding by default, but Postman sends the request as is, so you need to manually encode it.

Some FHIR servers do handle the plain vertical bar character, but we cannot support it as it is a limitation of API Gateway:
> The plain text pipe character (|) is not supported for any request URL query string and must be URL-encoded. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html

**Comment by carvantes** [comment]
> I'm trying the search as defined in the FHIR 4 spec and it doesn't work.

The `:not` modifier is not currently supported.

---

> Is there any documentation on AWS FHIR Works search available?

Sorry, currently there is none. We've got similar feedback from other customers and we have plans to add better documentation to this package soon.

**Comment by phackwer** [comment]
Ok, this answered a lot. :-) Thanks for this. Closing this and waiting for the documentation and/or the complete search implementation as defined by FHIR. Cheers
