### ISSUE TITLE
Alternatives to DynamoDB

### ISSUE THREAD

**Issue by phackwer** [awslabs/fhir-works-on-aws-deployment#313]
Hi, is there an easy alternative to DynamoDB in the current setup? Is it possible to replace it to use a MongoDB server or any other similar document db? We would like to block access to the Items tab on the DynamoDB even to Root Admins on the AWS Console, is it possible?

**Comment by rsmayda** [comment]
> is there an easy alternative to DynamoDB in the current setup?

Probably the next "easiest" implementation is to switch DynamoDB to S3 or perhaps Mongo. Effectively you would want to re-create the https://github.com/awslabs/fhir-works-on-aws-persistence-ddb package to fit the data store you have in mind (implementing this interface: https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/persistence.ts).

> We would like to block access to the Items tab on the DynamoDB even to Root Admins on the AWS Console, is it possible?

Two off the top of my head:

1. you could add an explicit 'Deny' access to the DDB table in the admin IAM roles used to sign into the AWS account
2. you could encrypt the data being store in DDB (making the seen data obfuscated) (also called client side encryption)

**Comment by phackwer** [comment]
Hi Robert, thanks for this reply. So, in summary, out of the box there is no replacement? How would the replacement by MySQL or PostgreSQL affect the indexing of content done by ElasticSearch? What exactly is involved on writing the new component? Is it just following the provided interface and do the inner coding for the persistence? Would it work transparently for the REST api for the resources?

**Comment by rsmayda** [comment]
> out of the box there is no replacement? 

Yep that is right out of the box no replacement

> How would the replacement by MySQL or PostgreSQL affect the indexing of content done by ElasticSearch? 

If an insert into these databases could "trigger" the sync lambda I believe you could still use this approach (writing your own [sync](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/tree/mainline/src/ddbToEs)). Another note: the reason for FHIR Works using ES is that Dynamo is not searchable. Since you are looking at a RDS you could also rewrite the the search component to just query the RDS instead of using ES.

> What exactly is involved on writing the new component?

Implementing the [interface](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/persistence.ts) and passing it into your deployment config: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L33. There is no explicit requirement for you publishing your own component to NPM and if you are "demoing" I would suggest developing this component within the "deployment" package and you can shift this code out down the road if need arises.

> Would it work transparently for the REST api for the resources?

Yes! The Router uses the given config, so if you change the persistence component the router will call that instead.

**Comment by Zambonilli** [comment]
You might be able to replace dynamoDB with ScyllaDB with minimal code change to the existing dynamoDB persistence implementation. However, you're on the hook for building and maintaining the scyllaDB cluster.

https://www.scylladb.com/

**Comment by phackwer** [comment]
The idea would be to use Aurora instead. Thanks anyway. Closing as it was answered already.
