### ISSUE TITLE
[Bug] Resource Limited Exceeded in /auditLogMover/handler.ts

### ISSUE THREAD

**Issue by chrismrgn** [awslabs/fhir-works-on-aws-deployment#423]
**Describe the bug**
When running the handler the export fails with error `Resource limit exceeded`. It seems the limit is one 'RUNNING' or 'PENDING' task per account as described here https://console.aws.amazon.com/servicequotas/home/services/logs/quotas/L-EEC839DF

**To Reproduce**
1. Run handler against AWS account

**Expected behavior**
Handler to execute without exception

**Comment by nguyen102** [comment]
Thanks for the question. I see that you're unable to export the logs because the limit for number of Active Exports is reached. By default the AuditLogMover runs the export job once a day, with the expectation that the job takes less then two hours to complete.

Therefore it's expected that at most only one job will be run at a time. Are there other services in your AWS account that are running CWL export jobs? If yes, they may be running at the same time as the AuditLogMover. To allow AuditLogMover to run by itself, you can edit the code [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/cf541b0c7c741d1eb8d1ee91967481047b7e58c2/auditLogMover/serverless.yaml#L63) to change the export job schedule.

**Comment by chrismrgn** [comment]
Hi 

Sorry I did not reply in time. I missed the response to my original question.

I have tried running your lambda in our environment and I get the same result `Resource limit exceeded` error.

As I interpret your code, it creates 7 promises for a given log group and executes `createExportTask` in parallel. This causes the `Resource limit exceeded` error as AWS only allow 1 `PENDING` or `RUNNING` task per account and the code creates 7 in very quick succession. The only way it would not error is if the log volume is VERY low and somehow it managed to finish each export before the next started (very unlikely).

Have you experience this, and are you still running this code in your environment. I am looking to implement something similar and hoping to find out if you changed approach or there is something else I am missing?

Thanks,

**Comment by nguyen102** [comment]
From the [code](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/auditLogMover/handler.ts#L22-L35), it looks like the export job is only exporting one job a day.

It exports logs that are 7 days old and exactly one day worth of logs. So for example, if today is September 8, it only exports logs for September 1.

In line 30 `const endTimeMoment = beginTimeMoment.endOf('day');`  it is grabbing the timestamp for the end of the day on "September 1"
