### ISSUE TITLE
[Misc] Got ResourceNotFoundException error at audit-log-mover-poc-exportCloudwatchLogs

### ISSUE THREAD

**Issue by rhinozD** [awslabs/fhir-works-on-aws-deployment#498]
**What's on your mind?**
I've got this error when I check audit-log-mover-poc-exportCloudwatchLogs LogGroup. 
`ERROR	Failed to kick off all export tasks ResourceNotFoundException: The specified log group does not exist.`

Is this a bug or just I did mistake somewhere?
I found that the log group which is exported here not exist in CloudWatch.
```
      CloudwatchExecutionLogGroup:
        Description: Cloudwatch Execution log group for storing request/responses for auditing purposes
        Value: !Join ['', ['API-Gateway-Execution-Logs_', !Ref ApiGatewayRestApi, '/', !Ref Stage]]
        Export:
          Name: !Join ['-', [CloudwatchExecutionLogGroup, !Ref Stage]]
```
[](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L794-L798)
and the API Gateway executionLogging is disabling.
`executionLogging: false`
[](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L78)
**Versions (please complete the following information):**
 - v3.1.0

**Comment by maghirardelli** [comment]
Hello @rhinozD,

Thank you for bringing this to our attention. We believe this is a bug and are looking into this now. We'll work on the fix soon.

Thanks,
Marianna

**Comment by carvantes** [comment]
Hi,

This issue was fixed on https://github.com/awslabs/fhir-works-on-aws-deployment/pull/503. 

Note that after applying the fix, new logs will be exported to S3 as usual, but old logs that were not exported will remain in CloudWatch. You can move the old logs to s3 with the `create-export-task` API: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3ExportTasks.html
