### ISSUE TITLE
why integation tests are done before fhir works deployment?

### ISSUE THREAD

**Issue by nirojshrestha019** [awslabs/fhir-works-on-aws-deployment#531]
**What's on your mind?**
It seems that [`yarn run release`](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/scripts/install.sh#L309)  command runs integration-tests. But I am a little bit confused why it is being tested before the actual [serverless-deploy](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/scripts/install.sh#L318) fhirworks deployment command? Although there are no critical issues in re-deployment of fireworks into AWS, this integration test is failing in codebuild with the following error as
```
throw new Error('SMART_AUTH_ADMIN_USERNAME environment variable is not defined');

at getFhirClient (integration-tests/utils.ts:66:15)
at integration-tests/search.test.ts:23:3
```

How come I know these [conts](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/integration-tests/utils.ts#L53) values before the fhir-works deployment? Am I missing something here? 

Thanks.

**Versions (please complete the following information):**
 - v4.1.0 (smart-mainline)

**Comment by carvantes** [comment]
Hi,

`yarn run release` does not run integration tests. It only runs unit tests. There is a different script `yarn run int-test` to run integ tests

https://github.com/awslabs/fhir-works-on-aws-deployment/blob/79e90276fc5b4ba977cd8970e98c1f076a1858e9/package.json#L19-L26

I wasn't able to reproduce the issue of integ tests running before deployment with the default install script. Maybe the issue is specific to your setup. Double check that there are no  local changes to the install script and that no other test commands are being run(i.e. running `jest` is probably something you don't want to do since it runs both unit tests AND integ tests).

If you attach your console output we can look further into the issue.

**Comment by nirojshrestha019** [comment]
Thank you for the clarification @carvantes . Here is the copy paste of the codebuild log where integration-test runs: 

```
Okay, let's redeploy the server.
Setup will proceed with the following parameters: 
  Issuer Endpoint: 
  OAuth2 API Endpoint: 
  Patient Picker Endpoint: https://21rz241qw7.execute-api.us-west-2.amazo**ws.com/sbx
  Stage: sbx
  Region: us-west-2

yarn install v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package ma**gers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@1.7.2"
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@~1.7.2"
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@1.7.2"
success Already up-to-date.
Done in 0.87s.
yarn run v1.22.17
$ yarn run build && yarn run lint && yarn run test
$ tsc
$ eslint . --ext .ts,.tsx
$ jest --silent --passWithNoTests --testPathPattern=src/*
FAIL integration-tests/search.test.ts (9.51 s)
  ● search › search for various valid parameters
    SMART_AUTH_USERNAME environment variable is not defined
      64 |     } = process.env;
      65 |     if (SMART_AUTH_USERNAME === undefined) {
    > 66 |         throw new Error('SMART_AUTH_USERNAME environment variable is not defined');

```

But, if I replace [`yarn run release`](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/scripts/install.sh#L309) with `yarn run build` from install.sh then the integration tests are not run as seen in codebuild logs. 

Thus, it seems like `yarn run release` command is running the integration-tests in codebuild. Or please do let me know if I am missing something.

**Comment by carvantes** [comment]
`yarn run release` runs `yarn run test` which in turn runs `jest --silent --passWithNoTests --testPathPattern=src/*`

the jest command is not working properly on your environment. It seems to be ignoring the `--testPathPattern=src/*` arg. It shouldn't run integ tests since those are on the `integration-test/` folder and not under `src/*`. I'm unable to reproduce this issue locally.

Looks like the issue is specific to your setup. A couple things to try:

- Which version of `jest` are you using(check with `yarn run jest -v`)? It should be `26.6.3` but maybe you somehow ended with an older version.
- You have a warning of `warning package-lock.json found. Your project contains lock files generated by tools other than Yarn.` This indicates that some dependencies were installed with `npm` and may not match the version we are using. I suggest you delete `node_modules` and `package-lock.json` and reinstall the dependencies with `yarn install`.
- Which OS is it running on? (is it Windows?)

**Comment by nirojshrestha019** [comment]
Thank you for the response. I did delete the `package-lock.json` file and updated the `jest` version to `26.6.3` but still `yarn run release` is doing an integration test which results in errors as above. I am running the scrips in a Linux environment. 

I was curious at what point of the installation of FWOA the integration test is ran if `yarn run release` is not supposed to run that test?

**Comment by carvantes** [comment]
The integ tests do not run as part of the FWOA installation. We run integ tests automatically before merging to `mainline`: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/08674d3e0c91143d14ac22dd60bc1b41dda425a6/.github/workflows/deploy.yaml#L198

Customers that wish to only install FWOA don't need to run integ tests, but the tests are available should they want to run them on a CI/CD setup.

Looks like it is an issue with jest: https://github.com/facebook/jest/issues/8226#issuecomment-591475185
Can you check if the path to your FWOA solution includes `src/`? The immediate workaround is to place the FWOA code in a path that does not contain `src/`. We'll look into updating our config to avoid this issue.

**Comment by lquanx** [comment]
Hi @carvantes , Thanks for your comments. I found a workaround which is 
`"test": "jest --silent --passWithNoTests --testPathPattern=\"$PWD/src\"",`
Do you mind me putting up a PR ?

**Comment by carvantes** [comment]
> Hi @carvantes , Thanks for your comments. I found a workaround which is `"test": "jest --silent --passWithNoTests --testPathPattern=\"$PWD/src\"",` Do you mind me putting up a PR ?

@Lin-002 ,thanks for the suggestion. It is a nice workaround but unfortunately it won't work on Windows. It actually messes up Windows since it prevents unit tests from running even if they are using a "normal" path that does not contain `src/`.

Ideally we want to commit a solution that works in both Linux and Windows.

**Comment by lquanx** [comment]
That makes sense.

**Comment by Zambonilli** [comment]
A cross platform solution here is to use the `--testPathIgnorePatterns` jest option pointed at the integration-tests/*. I'm on *nix so I can't confirm that Windows will break with this but it theoretically should work.
