### ISSUE TITLE
Custom tags to FHIR resources

### ISSUE THREAD

**Issue by vcareit** [awslabs/fhir-works-on-aws-deployment#613]
How to add custom tags as request to FHIR resources such as Patient and Observation ?

I wanted to add something like below in my postman request:

{
  "resourceType": "Patient",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p></p></div>"
  },
  "active": true,
  "name": [
    {
      "family": "testaddTag",
      "given": ["giventest"]
    }
  ],
  "gender": "male",
  "birthDate": "1980-09-21",
  "managingOrganization": {
    "reference": "Organization/ABC03",
    "display": "ABC03 Org"
  },
  "tag" : [ 
        {
            "system" : "hxxp://mydomain/fhir/custom_tag/AdditionalInfo",
            "Preference" : "Pref1"
        }
    ]

}

**Comment by Bingjiling** [comment]
Hi @vcareit ,

Thanks for reaching out! 

Are you looking to add a field extension `tag` to specific resource types or using the [Meta.tag](https://build.fhir.org/resource.html#Meta) field? 

Thanks,
Yanyu

**Comment by vcareit** [comment]
Hi @Bingjiling 

Yes I am looking to add field extension tag to a specific resource. E.g. For Patient resource if I need to capture an extra element on the UI then I would prefer it to be stored along with the patient resource rather than into an another table. In my example above its a tag array.

regards
Aman

**Comment by nguyen102** [comment]
Hi @vcareit , 

To add a new field to a resource, you will need to update the validator to accept the new schema for that resource. The configuration for the schema is located [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L44).

If there is an IG that supports the `tag` field, you can follow the instructions [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md) to use that IG. Otherwise, you can define a new schema for your resource and update the [JSON schema validator](https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/validation/jsonSchemaValidator.ts).
