### ISSUE TITLE
--enableMultiTenancy switch displays a warning.

### ISSUE THREAD

**Issue by viperx77** [awslabs/fhir-works-on-aws-deployment#633]
When I execute serverless per the documentation:

`serverless deploy --stage dev --region us-west-2 --enableMultiTenancy true`

I see the warning:

`Deprecation warning: Detected unrecognized CLI options: "--enableMultiTenancy"`

Is that flag properly supported? Sorry. I'm unfamiliar with serverless and how it passes switches down. Is this expected?

**Comment by ssvegaraju** [comment]
Hi @viperx77, this is an expected warning since `--enableMultiTenancy` isn't a flag supported by serverless directly. This is a custom parameter we've defined, and it should correctly be processed when supplied (you can verify this by checking the environment variables under the `Configuration` tab for any of the deployed lambda functions that are part of the stack to see whether the `ENABLE_MULTI_TENANCY` variable is set correctly). Hope this helps!
