### ISSUE TITLE
[Bug] Fails to deploy on new AWS account

### ISSUE THREAD

**Issue by liaden** [awslabs/fhir-works-on-aws-deployment#711]
**Describe the bug**
Deployment against a fresh account (with the a concurrent lambda limit of 10) fails.

**To Reproduce**
1. Create new account.
2. Run `yarn deploy`.
4. Error message is shown about exceeding the concurrent lambda limit.
5. Rollback doesn't rollback everything.
6. Running `yarn run cdk destroy` does not destroy everything.
7. I have to attempt a redeploy to find the leftover resources to delete via the AWS console (log groups and dynamo db tables).

**Expected behavior**
1. Check that the limits have enough capacity prior to running? Obviously other things could get provisioned and things still fail, but it'd be nice to avoid a gotcha.
2. Some logging at the end that reports orphaned resources, or some recommendation for ease of identifying the orphaned resources.

**Screenshots**
N/A

**Versions (please complete the following information):**
Commit Hash: bdde5c244ed3d84d65f93484861a52f45bef255e

**Additional context**
N/A

**Comment by ssvegaraju** [comment]
Hi, thanks for bringing this up!
1. This is something we can look into making a check for, but by default new AWS Accounts have limited provisioned concurrency capacity. You can open a request with AWS Support to increase your account's provisioned concurrency lambda limit.
2. We do retain some resources by default by design even through deletion. This is so that data is not lost in the case of accidental stack deletion. However, I will add an action to our backlog to make more clear in our documentation which resources are retained in the case of stack deletion. Thanks for calling that out!

Best,
Sukeerth

**Comment by liaden** [comment]
Yeah, this was mostly an issue of letting y'all know in case others spin up an account for testing purposes to avoid some additional frustrations.
