### ISSUE TITLE
Echoing Concern With The 400KB Limit

### ISSUE THREAD

**Issue by matthewjcable** [awslabs/fhir-works-on-aws-deployment#718]
**Is your feature request related to a problem? Please describe.**
I need to echo the concerns about the current 400KB record limitation discussed previously:

- [deployment/issues/709](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/709)
- [deployment/issues/595](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/595)

As my company begins to take in FHIR from a wide variety of other companies, we are now encountering resources that go beyond the 400KB limit.   We are going to have to find a solution very soon.

**Describe the solution you'd like**
A solution that would either leverage:
- Compression - Discussed in the Persistence project.   Depending upon effectiveness, this could help in the short term.
- Different database technology, supporting larger object sizes, enabled via a provided alternate Persistence interface
- Pointer in Dynamo, to a resource in another DB technology that can handle larger object sizes.  This would need to seamlessly handle all CRUD operations.

**Describe alternatives you've considered**
- Writing our own persistence layer to DocumentDB or MongoDB - This is not a trivial exercise, especially for search.  We will probably not take this route.
-  Moving to another FHIR Server solution - I do not want to, but we are seriously looking at other options.

**Additional context**
None at this time.

**Comment by ssvegaraju** [comment]
Hi @matthewjcable, thanks for bringing up this issue! At the moment, we don't have any plans to make a separate database implementation. We offer the [persistence interface](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/persistence.ts#L55), which provides the guidelines by which to write a separate persistence layer. In addition, we also offer the [facade implementation](https://github.com/awslabs/fhir-works-on-aws-persistence-facade), which wraps persistence operations to communicate with Integration Microservices, which may fit your use case. This is otherwise a good example of a separate package that implements the persistence interface.

Thanks, 
Sukeerth

**Comment by maghirardelli** [comment]
Closing this issue as the ability for FHIR Works to use an alternate persistence layer is already available.
