### ISSUE TITLE
[Question] Unauthorized Error Posting Binary

### ISSUE THREAD

**Issue by sunitakodali** [awslabs/fhir-works-on-aws-deployment#728]
Hello There,

Trying to post Patient/Practitioner/Binary postman examples. I am getting error as Unauthorized. 

Thank you.

**Comment by Bingjiling** [comment]
Hi @sunitakodali,

Thanks for reaching out! 

Are you getting the same Unauthorized error posting to other FWoA endpoints as well? Or is the binary endpoint the only you're having trouble with? 

Meanwhile, could you please share more details on the POST request you sent? 

Thanks,
Yanyu

**Comment by sunitakodali** [comment]
Hello Yanyu,

I am getting the same error message on all other endpoints as well. The only request that worked was, Get Metadata (since it didn't required API_KEY). I am providing all the required information like Cognito_Key, API_Key and API_URL. For the Cognito Key, I am providing ID_Token instead of Access Token. I tried both too but getting the same error: "Unauthorized". For ID_token, getting error message in FHIR message format, and for Access Token, just Json format.

Thank you,
Sunita

**Comment by Bingjiling** [comment]
Hi Sunita,

Thanks for the information!

Are you using the provided [PostMan collection and environment files](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/mainline/postman)? There are some mismatches in names and upper/lower cases in the parameter names you provided. Meanwhile, the Cognito token should be a plain string instead of a Json.  

Thanks,
Yanyu
