### ISSUE TITLE
[Misc] Why do we have `xpath` requirement ?

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-deployment#769]
**What's on your mind?**
`yarn run compile-igs` requires both `FHIRPath` and `XPath` for SearchParameter custom IG. I'm wondering why do we need both ? The latest [IG Publisher](https://github.com/HL7/fhir-ig-publisher) actually removes `XPath` intentionally. And our custom IGs would fail to compile because of absence of `XPath`. Isn't `XPath` redundant, since we have `FHIRPath` already ? HL7 also intends to remove the xpath element in an upcoming release of FHIR. 

Can we remove requirement of `xpath` ? 
Thanks very much !

**Comment by nguyen102** [comment]
Hi, 

Both `FHIRPath` and `XPath` are required because `FHIRPath` does not contain the type information in the search param expression. `Xpath` includes the type information. By combining `FHIRPath` and `Xpath` we can more accurately define the search param for ES. More details [here](https://github.com/awslabs/fhir-works-on-aws-search-es/pull/44)

Can you include the link where HL7 states that they will remove `xpath` elements in future release? This will help us prioritize implementing this request.

Thanks,
Tim

**Comment by lquanx** [comment]
Thanks for your reply.
In the FHIR R5, there is no more xpath element in SearchParameter resource. Here is the [link](https://build.fhir.org/searchparameter.html)

**Comment by nguyen102** [comment]
Thank you, I'll add this to our backlog

**Comment by ElliotSilver** [comment]
@nguyen102 -- Regarding priority, @lquanx mentions that the latest IG publisher actually strips xpath information from the resource, so this is not a R5 issue; we're experiencing it currently with R4. I'd also hesitate to call this an enhancement, since it is a regression in the toolchain (whether that's a FWOA issue or an IG publisher issue, I'll let others decide).

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
